### PR TITLE
Play-2.6.x support

### PR DESCRIPTION
**Pull request by helllamer**
Works for me.
Thanks.

### CODE REVIEW

**Comment by helllamer** [comment]
`scala-sampleapp` fixed, test spec totally rewritten.
java ... will try to do

**Comment by julienrf** [comment]
Hi, thanks!

That looks good, can you also update the .travis file to test only for scala 2.11.8 and 2.12.1? See [here](https://docs.travis-ci.com/user/languages/scala/#Choosing-Scala-versions-to-test-against).

**Comment by helllamer** [comment]
Ok, will do.
I'll fix java tests and reply.

**Comment by julienrf** [comment]
Thanks @helllamer

**Comment by julienrf** [comment]
I published the 3.0.0 version.

**Comment by helllamer** [comment]
Very good.
Thanks.

**Pull request merged**
